## Observations and Insights

In [115]:
# Dependencies and Setup
%matplotlib notebook
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as sts
import numpy as np

# Study data files
mouse_metadata_path = "data/Mouse_metadata.csv"
study_results_path = "data/Study_results.csv"

# Read the mouse data and the study results
mouse_metadata = pd.read_csv(mouse_metadata_path)
study_results = pd.read_csv(study_results_path)

# Combine the data into a single dataset
full_data=pd.merge(mouse_metadata,study_results, how='left',on=['Mouse ID','Mouse ID'])

# Display the data table for preview
full_data.head()

,Mouse ID,Drug Regimen,Sex,Age_months,Weight (g),Timepoint,Tumor Volume (mm3),Metastatic Sites
0,k403,Ramicane,Male,21,16,0,45.000000,0
1,k403,Ramicane,Male,21,16,5,38.825898,0
2,k403,Ramicane,Male,21,16,10,35.014271,1
3,k403,Ramicane,Male,21,16,15,34.223992,1
4,k403,Ramicane,Male,21,16,20,32.997729,1

In [116]:
# Checking the number of mice.
num_mice=full_data.loc[:,"Mouse ID"].drop_duplicates()
len(num_mice)

249

In [132]:
# Getting the duplicate mice by ID number that shows up for Mouse ID and Timepoint. 
##clean_mice=full_data.sort_values(by=['Mouse ID','Timepoint'])
##clean_mice.head()

#duplicate_mice_filter=full_data.duplicated(subset=['Mouse ID','Timepoint'],keep=False)==True
#duplicate_mice_df=full_data.loc[duplicate_mice_filter,:]
#unique_mice_filter=full_data.duplicated(subset=['Mouse ID','Timepoint'],keep=False)!=True
#unique_mice_df=full_data.loc[unique_mice_filter,:]
#unique_mice_df.head()
#duplicate_mice_df
duplicate_mouse=full_data.loc[full_data.duplicated(subset=['Mouse ID','Timepoint']),'Mouse ID'].unique()
#test=full_data[full_data["Mouse ID"]== 'g989'
df=full_data[full_data["Mouse ID"].isin(duplicate_mouse) == False]
df

,Mouse ID,Drug Regimen,Sex,Age_months,Weight (g),Timepoint,Tumor Volume (mm3),Metastatic Sites
0,k403,Ramicane,Male,21,16,0,45.000000,0
1,k403,Ramicane,Male,21,16,5,38.825898,0
2,k403,Ramicane,Male,21,16,10,35.014271,1
3,k403,Ramicane,Male,21,16,15,34.223992,1
4,k403,Ramicane,Male,21,16,20,32.997729,1
...,...,...,...,...,...,...,...,...
1888,z969,Naftisol,Male,9,30,25,63.145652,2
1889,z969,Naftisol,Male,9,30,30,65.841013,3
1890,z969,Naftisol,Male,9,30,35,69.176246,4
1891,z969,Naftisol,Male,9,30,40,70.314904,4
1892,z969,Naftisol,Male,9,30,45,73.867845,4

In [133]:
new_count=len(clean_df['Mouse ID'].unique())
new_count

248

## Summary Statistics

In [134]:
# Generate a summary statistics table of mean, median, variance, standard deviation, and SEM of the tumor volume for each regimen
# Use groupby and summary statistical methods to calculate the following properties of each drug regimen: 
# mean, median, variance, standard deviation, and SEM of the tumor volume. 
# Assemble the resulting series into a single summary dataframe.

#####FILTER 

mean=df['Tumor Volume (mm3)'].mean()
median=df['Tumor Volume (mm3)'].median()
#variance=np.var(df['Tumor Volume (mm3)'])
variance=df['Tumor Volume (mm3)'].var()
#variance_2=sts.variation(df['Tumor Volume (mm3)'])
std=np.std(df['Tumor Volume (mm3)'])
sem=sts.sem(df['Tumor Volume (mm3)'])

print(f'The mean of the tumor volume clean mouse set is {mean}')
print(f'The median of the tumor volume clean mouse set is {median}')
print(f'The variance of the tumor volume clean mouse set is {variance}')
print(f'The Standard Deviation of the tumor volume clean mouse set is {std}')
print(f'The Standard Error Mean of the tumor volume clean mouse set is {sem}')
data={"Tumor Mean": [mean],
     "Tumor Median": [median],
     "Tumor Variance": [variance], ##correct variance?
     "Tumor Standard Dev": [std],
     "Tumor SEM":[sem]}

tumor_stats=pd.DataFrame(data)
tumor_stats

The mean of the tumor volume clean mouse set is 50.435293232255326
The median of the tumor volume clean mouse set is 48.933453655
The variance of the tumor volume clean mouse set is 79.46290714557298
The Standard Deviation of the tumor volume clean mouse set is 8.911825830982792
The Standard Error Mean of the tumor volume clean mouse set is 0.20559062186986257

   Tumor Mean  Tumor Median  Tumor Variance  Tumor Standard Dev  Tumor SEM
0   50.435293     48.933454       79.462907            8.911826   0.205591

In [135]:
drug_df=df[['Drug Regimen','Tumor Volume (mm3)']]
drug_df=drug_df.groupby('Drug Regimen')

mean=drug_df.mean()
median=drug_df.median()
variance=drug_df.var()
#variance_2=sts.variation(drug_df)
std=drug_df.std()
sem=drug_df.sem()
#data={"Tumor Mean": [mean],
 #    "Tumor Median": [median],
  #   "Tumor Variance": [variance], ##correct variance?
   #  "Tumor Standard Dev": [std],
    # "Tumor SEM":[sem]}
data={"Tumor Mean": mean['Tumor Volume (mm3)'],
     "Tumor Median": median['Tumor Volume (mm3)'],
     "Tumor Variance": variance['Tumor Volume (mm3)'], 
    "Tumor Standard Dev": std['Tumor Volume (mm3)'],
    "Tumor SEM":sem['Tumor Volume (mm3)']}
tumor_stats=pd.DataFrame(data)
tumor_stats

,Tumor Mean,Tumor Median,Tumor Variance,Tumor Standard Dev,Tumor SEM
Drug Regimen,,,,,
Capomulin,40.675741,41.557809,24.947764,4.994774,0.329346
Ceftamin,52.591172,51.776157,39.290177,6.268188,0.469821
Infubinol,52.884795,51.820584,43.128684,6.567243,0.492236
Ketapril,55.235638,53.698743,68.553577,8.279709,0.603860
Naftisol,54.331565,52.509285,66.173479,8.134708,0.596466
Placebo,54.033581,52.288934,61.168083,7.821003,0.581331
Propriva,52.320930,50.446266,43.852013,6.622085,0.544332
Ramicane,40.216745,40.673236,23.486704,4.846308,0.320955
Stelasyn,54.233149,52.431737,59.450562,7.710419,0.573111
Zoniferol,53.236507,51.818479,48.533355,6.966589,0.516398

In [37]:
# Generate a summary statistics table of mean, median, variance, standard deviation, and SEM of the tumor volume for each regimen
# Using the aggregation method, produce the same summary statistics in a single line

## Bar and Pie Charts

In [9]:
# Generate a bar plot showing the total number of measurements taken on each drug regimen using pandas.

In [10]:
# Generate a bar plot showing the total number of measurements taken on each drug regimen using pyplot.

In [11]:
# Generate a pie plot showing the distribution of female versus male mice using pandas

In [12]:
# Generate a pie plot showing the distribution of female versus male mice using pyplot

## Quartiles, Outliers and Boxplots

In [13]:
# Calculate the final tumor volume of each mouse across four of the treatment regimens:  
# Capomulin, Ramicane, Infubinol, and Ceftamin

# Start by getting the last (greatest) timepoint for each mouse


# Merge this group df with the original dataframe to get the tumor volume at the last timepoint

In [14]:
# Put treatments into a list for for loop (and later for plot labels)


# Create empty list to fill with tumor vol data (for plotting)


# Calculate the IQR and quantitatively determine if there are any potential outliers. 

    
    # Locate the rows which contain mice on each drug and get the tumor volumes
    
    
    # add subset 
    
    
    # Determine outliers using upper and lower bounds

In [15]:
# Generate a box plot of the final tumor volume of each mouse across four regimens of interest

## Line and Scatter Plots

In [16]:
# Generate a line plot of tumor volume vs. time point for a mouse treated with Capomulin

In [17]:
# Generate a scatter plot of average tumor volume vs. mouse weight for the Capomulin regimen

## Correlation and Regression

In [18]:
# Calculate the correlation coefficient and linear regression model 
# for mouse weight and average tumor volume for the Capomulin regimen